{% set name = "cpp-expected" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/TartanLlama/expected/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 8f5124085a124113e75e3890b4e923e3a4de5b26a973b891b3deb40e19c03cee
    patches:
    - CMakeLists.txt.patch
  - git_url: https://github.com/TartanLlama/tl-cmake.git
    git_rev: 284c6a3
    git_depth: 1 # (Defaults to -1/not shallow)
    folder: cmake/tl-cmake/

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - git
    - ninja
    - m2-patch  # [win]
    - patch  # [not win]

test:
  commands:
    - test -f ${PREFIX}/include/tl/expected.hpp  # [unix]
    - test -f ${PREFIX}/share/cmake/tl-expected/tl-expected-config.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/tl-expected/tl-expected-config-version.cmake  # [unix]
    - if not exist %LIBRARY_INC%\tl\expected.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\tl-expected\tl-expected-config.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\tl-expected\tl-expected-config-version.cmake (exit 1)  # [win]

about:
  home: https://github.com/TartanLlama/expected
  license: CC0-1.0
  license_family: CC
  license_file: COPYING
  summary: C++11/14/17 std::expected with functional-style extensions
  description: C++11/14/17 std::expected with functional-style extensions
  doc_url: https://github.com/TartanLlama/expected#readme
  dev_url: https://github.com/TartanLlama/expected

extra:
  recipe-maintainers:
    - JohanMabille
    - wolfv
